def just_init():
    pass
all_var_names = [
    'Renter Occupied',
    'Vacant Housing Units',
    'pop_sqmi',
    'IET',
    'Apparel Stores',
    'Thrift Stores',
    'pct_Moved from abroad',
    'pct_Different county same state',
    'pct_Moved from different state',
    'pct_Moved within same county',
    'pct_Same house 1 year ago',
    'pct_F_birth last 12 months',
    'Afghan',
    'Albanian',
    'Alsatian',
    'American',
    'Arabian',
    'Armenian',
    'Assyrian_Chaldean_Syriac',
    'Australian',
    'Austrian',
    'Basque',
    'Belgian',
    'Brazilian',
    'British',
    'Bulgarian',
    'Cajun',
    'Canadian',
    'Carpatho_Rusyn',
    'Celtic',
    'Croatian',
    'Cypriot',
    'Czech',
    'Czechoslovakian',
    'Danish',
    'Dutch',
    'Eastern_European',
    'English',
    'Estonian',
    'European',
    'Finnish',
    'French',
    'French_Canadian',
    'German',
    'German_Russian',
    'Greek',
    'Guyanese',
    'Hungarian',
    'Icelander',
    'Iranian',
    'Irish',
    'Israeli',
    'Italian',
    'Latvian',
    'Lithuanian',
    'Luxemburger',
    'Macedonian',
    'Maltese',
    'New_Zealander',
    'Northern_European',
    'Norwegian',
    'Other_groups',
    'Pennsylvania_German',
    'Polish',
    'Portuguese',
    'Romanian',
    'Russian',
    'Scandinavian',
    'Scotch_Irish',
    'Scottish',
    'Serbian',
    'Slavic',
    'Slovak',
    'Slovene',
    'Soviet_Union',
    'Subsaharan_African',
    'Swedish',
    'Swiss',
    'Turkish',
    'Ukrainian',
    'Welsh',
    'West_Indian',
    'Yugoslavian',
    'pct_Age_18plus',
    'pct_Age_21plus',
    'pct_Age_55plus',
    'pct_Age_65plus',
    'pct_Age_0to4',
    'pct_Age_5to9',
    'pct_Age_10to14',
    'pct_Age_15to17',
    'pct_Age_18to19',
    'pct_Age_20',
    'pct_Age_21',
    'pct_Age_22to24',
    'pct_Age_25to29',
    'pct_Age_30to34',
    'pct_Age_35to39',
    'pct_Age_40to44',
    'pct_Age_45to49',
    'pct_Age_50to54',
    'pct_Age_55to59',
    'pct_Age_60to61',
    'pct_Age_62to64',
    'pct_Age_65',
    'pct_Age_66',
    'pct_Age_67to69',
    'pct_Age_70to74',
    'pct_Age_75to79',
    'pct_Age_80to84',
    'pct_Age_85plus',
    'deat_pct_Age_minus_1_year',
    'deat_pct_Age_1',
    'deat_pct_Age_2',
    'deat_pct_Age_3',
    'deat_pct_Age_4',
    'deat_pct_Age_5',
    'deat_pct_Age_6',
    'deat_pct_Age_7',
    'deat_pct_Age_8',
    'deat_pct_Age_9',
    'deat_pct_Age_10',
    'deat_pct_Age_11',
    'deat_pct_Age_12',
    'deat_pct_Age_13',
    'deat_pct_Age_14',
    'deat_pct_Age_15',
    'deat_pct_Age_16',
    'deat_pct_Age_17',
    'deat_pct_Age_18',
    'deat_pct_Age_19',
    'pct_No_school',
    'pct_minus 4th grade',
    'pct_5th and 6th grade',
    'pct_7th and 8th grade',
    'pct_9th grade',
    'pct_10th grade',
    'pct_11th grade',
    'pct_12th grade no diploma',
    'pct_High school graduate_GED_or_alt',
    'pct_Some college minus 1 year',
    'pct_Some college 1 plus no degree',
    "pct_Associate degree",
    "pct_Bachelor degree",
    "pct_Master degree",
    'pct_Professional degree',
    'pct_Doctorate degree',
    'pct_3-Person Households',
    'pct_4-Person Households',
    'pct_5-Person Households',
    'pct_6-Person Households',
    'pct_7+ Person Households',
    'HH_inc_minus_10k',
    'HH_inc_10k-15k',
    'HH_inc_15k-20k',
    'HH_inc_20k-25k',
    'HH_inc_25k-30k',
    'HH_inc_30k-35k',
    'HH_inc_35k-40k',
    'HH_inc_40k-45k',
    'HH_inc_45k-50k',
    'HH_inc_50k-60k',
    'HH_inc_60k-75k',
    'HH_inc_75k-100k',
    'HH_inc_100k-125k',
    'HH_inc_125k-150k',
    'HH_inc_150k-200k',
    'HH_inc_200k-250k',
    'HH_inc_250k-500k',
    'HH_inc_500k+',
    'pct_Age 18plus',
    'Hispanic/Latino Below Poverty Level',
    'American Indian and Alaskan Native Below Poverty Level',
    'Asian Below Poverty Level',
    'Black Below Poverty Level',
    'rat_inc_pov: minus 50',
    'rat_inc_pov: pt50_pt99',
    'rat_inc_pov: 1pt00_1pt24',
    'rat_inc_pov: 1pt25_1pt49',
    'rat_inc_pov: 1pt50_1pt84',
    'rat_inc_pov: 1pt85_1pt99',
    'rat_inc_pov: 2pt00+',
    'home_value_minus_10k',
    'home_value_10k-15k',
    'home_value_15k-20k',
    'home_value_20k-25k',
    'home_value_25k-30k',
    'home_value_30k-35k',
    'home_value_35k-40k',
    'home_value_40k-50k',
    'home_value_50k-60k',
    'home_value_60k-70k',
    'home_value_70k-80k',
    'home_value_80k-90k',
    'home_value_90k-100k',
    'home_value_100k-125k',
    'home_value_125k-150k',
    'home_value_150k-175k',
    'home_value_175k-200k',
    'home_value_200k-250k',
    'home_value_250k-300k',
    'home_value_300k-400k',
    'home_value_400k-500k',
    'home_value_500k-750k',
    'home_value_750k-100k',
    'home_value_1m_plus',
    'total_pct_ag_forest_hunt_mine',
    'pct_Agriculture_forestry_fishing_hunting',
    'pct_Mining_quarrying_oil_gas',
    'pct_Transportation_and_warehousing',
    'pct_transport_warehouse__Utilities',
    'pct_Finance and ins',
    'pct_real estate',
    'pct_Professional_sci_tech_svcs',
    'pct_Mgmt_of_companies_and_enterprises',
    'pct_Admin and support and waste mgmt svcs',
    'pct_Educational svcs',
    'pct_Health care and social asst',
    'pct_Arts, entertainment, recreation',
    'pct_Accommodation and food svcs',
    'Construction',
    'Manufacturing',
    'Wholesale trade',
    'Retail trade',
    'Transportation and warehousing and utilities',
    'Information',
    'Finance and ins, real estate, rental and leasing',
    'Professional_sci_mgmt_admin and waste mgmt svcs',
    'Educational svcs_health care and social asst',
    'Arts, entertainmnt_recreation_accom_and food svcs',
    'Other svcs_except public admin',
    'Public admin',
    'Motor Vehicle & Parts Dealers',
    'Furniture & Home Furnishings Stores',
    'Electronics and Appliance Stores',
    'Building Material & Garden Equipment & Supply Dealers',
    'Food & Beverage Stores',
    'Health & Personal Care Stores',
    'Gasoline stations',
    'Clothing & Clothing Accessories Stores',
    'Sporting Goods_Hobby_Musical Instrument_Book Stores',
    'General Merchandise Stores',
    'Miscellaneous Store Retailers',
    'Nonstore retailers',
    'Food Services and Drinking Places',
    'General Merchandise_Apparel and Accessories_Furniture and Other Sales',
    'Motor Vehicle & Parts Dealers Automotive Dealers',
    'Motor Vehicle & Parts Dealers Other Motor Vehicle Dealers',
    'Motor Vehicle & Parts Dealers Automotive Parts_Accessories_& Tire Stores',
    'Furniture Stores',
    'Furnishing Stores',
    'Home Furnishing Stores Floor Covering Stores',
    'Other Home Furnishings Stores',
    'Household appliance stores',
    'Electronics Stores',
    'Total Building Material & Supply Dealers',
    'Dealers Home Centers',
    'Dealers Paint and Wallpaper Stores',
    'Hardware Stores',
    'Other Building Materials Dealers',
    'Total Lawn and Garden Equipment and Supplies Stores',
    'Outdoor Power Equipment Stores',
    'Nursery and Garden centers',
    'Food and Beverage Stores Total Grocery Stores',
    'Grocery Stores Supermarkets_except Convenience',
    'Convenience Stores',
    'Food Stores',
    'Beer, Wine, & Liquor Stores',
    'Pharmacies and Drug Stores',
    'Cosmetics Beauty Supplies and Perfume Stores',
    'Optical Goods Stores',
    'Other Health and Personal Care Stores',
    'Total Clothing Stores',
    "Men's Clothing Stores",
    "Women's Clothing Stores",
    "Children's and Infants' Clothing Stores",
    'Family Clothing Stores',
    'Clothing Accessories Stores',
    'Other Clothing Stores',
    'Shoe Stores',
    'Jewelry Luggage & Leather Goods Stores',
    'Jewelry Stores',
    'Leather Goods Stores',
    'Total Sporting Goods Hobby & Musical Instrument Stores',
    'Sporting Goods Stores',
    'Hobby Toys and Games Stores',
    'Sew_Needlework_Piece Goods Stores',
    'Musical Instrument and Supplies Stores',
    'Total Book Stores and News Dealers',
    'Book Stores',
    'News Dealers and Newsstands',
    'Total Department Stores',
    'Total Other General Merchandise Stores',
    'Warehouse Clubs and Super Stores',
    'General Merchandise Stores_main',
    'Florists',
    'Total Office Supplies Stationery & Gift Stores',
    'Office Supplies and Stationery Stores',
    'Novelty and Souvenir Stores',
    'Used Merchandise Stores',
    'Total Other Miscellaneous Store Retailers',
    'Total Special Food Services',
    'Alcoholic Beverages services',
    'Eating Places',
    'CASS_StateAK',
    'CASS_StateAL',
    'CASS_StateAZ',
    'CASS_StateCA',
    'CASS_StateCO',
    'CASS_StateCT',
    'CASS_StateDE',
    'CASS_StateFL',
    'CASS_StateGA',
    'CASS_StateHI',
    'CASS_StateIA',
    'CASS_StateIL',
    'CASS_StateIN',
    'CASS_StateKS',
    'CASS_StateKY',
    'CASS_StateLA',
    'CASS_StateMA',
    'CASS_StateMD',
    'CASS_StateME',
    'CASS_StateMI',
    'CASS_StateMN',
    'CASS_StateMO',
    'CASS_StateMS',
    'CASS_StateNC',
    'CASS_StateNE',
    'CASS_StateNH',
    'CASS_StateNJ',
    'CASS_StateNV',
    'CASS_StateNY',
    'CASS_StateOH',
    'CASS_StateOK',
    'CASS_StateOR',
    'CASS_StatePA',
    'CASS_StateRI',
    'CASS_StateTN',
    'CASS_StateTX',
    'CASS_StateVA',
    'CASS_StateWA',
    'CASS_StateWI',
    'emps_Agriculture Forestry Fishing and Hunting (11)',
    'emps_Mining Quarrying and Oil and Gas Extraction (21)',
    'emps_Utilities (22)',
    'emps_Construction (23)',
    'emps_Manufacturing (31)',
    'emps_Manufacturing (32)',
    'emps_Manufacturing (33)',
    'emps_Wholesale Trade (42)',
    'emps_Retail Trade (44)',
    'emps_Retail Trade (45)',
    'emps_Transportation and Warehousing (48)',
    'emps_Transportation and Warehousing (49)',
    'emps_Information (51)',
    'emps_Finance and Insurance (52)',
    'emps_Real Estate and Rental and Leasing (53)',
    'emps_Professional Scientific and Technical Services (54)',
    'emps_Management of Companies and Enterprises (55)',
    'emps_Administrative and Support and Waste Management(56)',
    'emps_Educational Services (61)',
    'emps_Health Care and Social Assistance (62)',
    'emps_Arts Entertainment and Recreation (71)',
    'emps_Accommodation and Food Services (72)',
    'emps_Other Services (except Public Administration) (81)',
    'emps_Public Administration (92)',
    'est_Agriculture, Forestry, Fishing and Hunting (11)',
    'est_Mining, Quarrying, and Oil and Gas Extraction (21)',
    'est_Utilities (22)',
    'est_Construction (23)',
    'est_Manufacturing (31)',
    'est_Manufacturing (32)',
    'est_Manufacturing (33)',
    'est_Wholesale Trade (42)',
    'est_Retail Trade (44)',
    'est_Retail Trade (45)',
    'est_Transportation and Warehousing (48)',
    'est_Transportation and Warehousing (49)',
    'est_Information (51)',
    'est_Finance and Insurance (52)',
    'est_Real Estate and Rental and Leasing (53)',
    'est_Professional Scientific and Technical Services (54)',
    'est_Management of Companies and Enterprises (55)',
    'est_Administrative and Support and Waste Management(56)',
    'est_Educational Services (61)',
    'est_Health Care and Social Assistance (62)',
    'est_Arts Entertainment and Recreation (71)',
    'est_Accommodation and Food Services (72)',
    'est_Other Services (except Public Administration) (81)',
    'est_Public Administration (92)',
    'A01 American Royalty',
    'A02 Platinum Prosperity',
    'A03 Kids and Cabernet',
    'A04 Picture Perfect Families',
    'A05 Couples with Clout',
    'A06 Jet Set Urbanites',
    'B07 Generational Soup',
    'B08 Babies and Bliss',
    'B09 Family Fun-tastic',
    'B10 Cosmopolitan Achievers',
    'C11 Aging of Aquarius',
    'C12 Golf Carts and Gourmets',
    'C13 Silver Sophisticates',
    'C14 Boomers and Boomerangs',
    'D15 Sports Utility Families',
    'D16 Settled in Suburbia',
    'D17 Cul de Sac Diversity',
    'D18 Suburban Attainment',
    'E19 Full Pockets, Empty Nests',
    'E20 No Place Like Home',
    'E21 Unspoiled Splendor',
    'F22 Fast Track Couples',
    'F23 Families Matter Most',
    'G24 Status Seeking Singles',
    'G25 Urban Edge',
    'H26 Progressive Potpourri',
    'H27 Birkenstocks and Beemers',
    'H28 Everyday Moderates',
    'H29 Destination Recreation',
    'I30 Stockcars and State Parks',
    'I31 Blue Collar Comfort',
    'I32 Steadfast Conventionalists',
    'I33 Balance and Harmony',
    'J34 Aging in Place',
    'J35 Rural Escape',
    'J36 Settled and Sensible',
    'K37 Wired for Success',
    'K38 Gotham Blend',
    'K39 Metro Fusion',
    'K40 Bohemian Groove',
    'L41 Booming and Consuming',
    'L42 Rooted Flower Power',
    'L43 Homemade Happiness',
    'M44 Red, White and Bluegrass',
    'M45 Diapers and Debit Cards',
    'N46 True Grit Americans',
    'N47 Countrified Pragmatics',
    'N48 Rural Southern Bliss',
    'N49 Touch of Tradition',
    'O50 Full Steam Ahead',
    'O51 Digital Dependents',
    'O52 Urban Ambition',
    'O53 Colleges and Cafes',
    'O54 Striving Single Scene',
    'O55 Family Troopers',
    'P56 Mid-scale Medley',
    'P57 Modest Metro Means',
    'P58 Heritage Heights',
    'P59 Expanding Horizons',
    'P60 Striving Forward',
    'P61 Humble Beginnings',
    'Q62 Reaping Rewards',
    'Q63 Footloose and Family Free',
    'Q64 Town Elders',
    'Q65 Senior Discounts',
    'R66 Dare to Dream',
    'R67 Hope for Tomorrow',
    'S68 Small Town Shallow Pockets',
    'S69 Urban Survivors',
    'S70 Tight Money',
    'S71 Tough Times',
    'U99 Unclassified'
]
