totals_cols = ['Furnishing Stores',
               'Total Building Material & Supply Dealers',
               'Total Lawn and Garden Equipment and Supplies Stores',
               'Food and Beverage Stores Total Grocery Stores',
               'Total Clothing Stores',
               'Jewelry Luggage & Leather Goods Stores',
               'Total Sporting Goods Hobby & Musical Instrument Stores',
               'Total Book Stores and News Dealers',
               'Total Other General Merchandise Stores',
               'Total Office Supplies Stationery & Gift Stores',
               'Total Special Food Services']

sal_sector_drop = ['est_Other Services (except Public Administration) (81)',
                   'emps_Other Services (except Public Administration) (81)']

eth_colnames = ['Afghan',
                'Albanian',
                'Alsatian',
                'American',
                'Arabian',
                'Armenian',
                'Assyrian_Chaldean_Syriac',
                'Australian',
                'Austrian',
                'Basque',
                'Belgian',
                'Brazilian',
                'British',
                'Bulgarian',
                'Cajun',
                'Canadian',
                'Carpatho_Rusyn',
                'Celtic',
                'Croatian',
                'Cypriot',
                'Czech',
                'Czechoslovakian',
                'Danish',
                'Dutch',
                'Eastern_European',
                'English',
                'Estonian',
                'European',
                'Finnish',
                'French',
                'French_Canadian',
                'German',
                'German_Russian',
                'Greek',
                'Guyanese',
                'Hungarian',
                'Icelander',
                'Iranian',
                'Irish',
                'Israeli',
                'Italian',
                'Latvian',
                'Lithuanian',
                'Luxemburger',
                'Macedonian',
                'Maltese',
                'New_Zealander',
                'Northern_European',
                'Norwegian',
                'Other_groups',
                'Pennsylvania_German',
                'Polish',
                'Portuguese',
                'Romanian',
                'Russian',
                'Scandinavian',
                'Scotch_Irish',
                'Scottish',
                'Serbian',
                'Slavic',
                'Slovak',
                'Slovene',
                'Soviet_Union',
                'Subsaharan_African',
                'Swedish',
                'Swiss',
                'Turkish',
                'Ukrainian',
                'Welsh',
                'West_Indian',
                'Yugoslavian']

detailed_ages = ['deat_pct_Age_minus_1_year',
 'deat_pct_Age_1',
 'deat_pct_Age_2',
 'deat_pct_Age_3',
 'deat_pct_Age_4',
 'deat_pct_Age_5',
 'deat_pct_Age_6',
 'deat_pct_Age_7',
 'deat_pct_Age_8',
 'deat_pct_Age_9',
 'deat_pct_Age_10',
 'deat_pct_Age_11',
 'deat_pct_Age_12',
 'deat_pct_Age_13',
 'deat_pct_Age_14',
 'deat_pct_Age_15',
 'deat_pct_Age_16',
 'deat_pct_Age_17',
 'deat_pct_Age_18',
 'deat_pct_Age_19',
                 # this random age group doesn't come from the same place
                 # as the others and it has a dup so we're dropping it
                 'pct_Age 18plus']

school_years = ['pct_minus 4th grade',
 'pct_5th and 6th grade',
 'pct_7th and 8th grade',
 'pct_9th grade',
 'pct_10th grade',
 'pct_11th grade',
 'pct_12th grade no diploma','pct_Associate degree', 'pct_Bachelor degree']

naics_emps = ['emps_Agriculture Forestry Fishing and Hunting (11)',
 'emps_Mining Quarrying and Oil and Gas Extraction (21)',
 'emps_Utilities (22)',
 'emps_Construction (23)',
 'emps_Manufacturing (31)',
 'emps_Manufacturing (32)',
 'emps_Manufacturing (33)',
 'emps_Wholesale Trade (42)',
 'emps_Retail Trade (44)',
 'emps_Retail Trade (45)',
 'emps_Transportation and Warehousing (48)',
 'emps_Transportation and Warehousing (49)',
 'emps_Information (51)',
 'emps_Finance and Insurance (52)',
 'emps_Real Estate and Rental and Leasing (53)',
 'emps_Professional Scientific and Technical Services (54)',
 'emps_Management of Companies and Enterprises (55)',
 'emps_Administrative and Support and Waste Management(56)',
 'emps_Educational Services (61)',
 'emps_Health Care and Social Assistance (62)',
 'emps_Arts Entertainment and Recreation (71)',
 'emps_Accommodation and Food Services (72)',
 'emps_Other Services (except Public Administration) (81)',
 'emps_Public Administration (92)']

# duplicate_industries = ['total_pct_ag_forest_hunt_mine',
#                         'Transportation and warehousing and utilities',
#                         'Finance and ins real estate rental and leasing',
#                         'Furnishing Stores',
#                         'Total Building Material & Supply Dealers',
#                         'Total Lawn and Garden Equipment and Supplies Stores',
#                         'Food and Beverage Stores Total Grocery Stores',
#                         'Total Clothing Stores',
#                         'Jewelry Luggage & Leather Goods Stores',
#                         'Total Sporting Goods Hobby & Musical Instrument Stores',
#                         'Total Book Stores and News Dealers',
#                         ]

all_cols_to_drop = [totals_cols, sal_sector_drop, eth_colnames, detailed_ages, school_years, naics_emps]
flattened_drop_vars_list = [item for sublist in all_cols_to_drop for item in sublist]
